name: CAB's kata
description: musings of a man on a journey
url: http://www.cabkata.com/blog
markdown: rdiscount
permalink: /:title.html
destination: ../../public/blog
auto: true
exclude:
  - Rakefile
  - Gemfile
  - .gitignore
